CREATE TABLE IF NOT EXISTS `battery_series` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `raw_dataset` VARCHAR(255) NOT NULL COMMENT '原始数据集标识，如 UPS/型号1、开关电源',
  `source_category` VARCHAR(64) NOT NULL COMMENT '来源大类，如 UPS、开关电源',
  `source_subtype` VARCHAR(128) DEFAULT NULL COMMENT '来源子类，如 型号1',
  `series_id` VARCHAR(512) NOT NULL COMMENT '序列稳定主键',
  `machine_room_id` INT DEFAULT NULL COMMENT '关联 machine_room.id，按机房名称/城市匹配',
  `province` VARCHAR(64) DEFAULT NULL COMMENT '省',
  `city` VARCHAR(64) DEFAULT NULL COMMENT '市',
  `site_name` VARCHAR(255) DEFAULT NULL COMMENT '站点',
  `building_name` VARCHAR(255) DEFAULT NULL COMMENT '楼栋',
  `room_name` VARCHAR(255) NOT NULL COMMENT '机房',
  `device_type` VARCHAR(128) DEFAULT NULL COMMENT '设备类型',
  `device_name` VARCHAR(255) NOT NULL COMMENT '设备',
  `point_type` VARCHAR(128) NOT NULL COMMENT '测点类型',
  `measure_name` VARCHAR(255) NOT NULL COMMENT '监控量',
  `group_name` VARCHAR(128) DEFAULT NULL COMMENT '组别',
  `point_code` VARCHAR(128) DEFAULT NULL COMMENT '测点编码',
  `unit` VARCHAR(64) DEFAULT NULL COMMENT '单位',
  `source_file` VARCHAR(255) NOT NULL COMMENT '来源 Excel 文件',
  `source_sheet` VARCHAR(128) DEFAULT NULL COMMENT '来源工作表',
  `first_report_time` DATETIME DEFAULT NULL COMMENT '首个上报时间',
  `last_report_time` DATETIME DEFAULT NULL COMMENT '最后上报时间',
  `sample_count` INT NOT NULL DEFAULT 0 COMMENT '样本点数',
  `latest_report_value` DOUBLE DEFAULT NULL COMMENT '最近一条上报值',
  `latest_monitor_value` DOUBLE DEFAULT NULL COMMENT '最近一条监控值',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_battery_series_dataset_series` (`raw_dataset`, `series_id`),
  KEY `idx_battery_series_room` (`room_name`),
  KEY `idx_battery_series_machine_room` (`machine_room_id`),
  KEY `idx_battery_series_point_type` (`point_type`),
  KEY `idx_battery_series_device` (`device_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='battery 原始序列元数据';

CREATE TABLE IF NOT EXISTS `battery_measurement` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `raw_dataset` VARCHAR(255) NOT NULL COMMENT '原始数据集标识',
  `source_category` VARCHAR(64) NOT NULL COMMENT '来源大类',
  `source_subtype` VARCHAR(128) DEFAULT NULL COMMENT '来源子类',
  `series_id` VARCHAR(512) NOT NULL COMMENT '序列稳定主键',
  `row_hash` CHAR(40) NOT NULL COMMENT '原始测点行哈希，避免重复导入',
  `machine_room_id` INT DEFAULT NULL COMMENT '关联 machine_room.id，按机房名称/城市匹配',
  `source_file` VARCHAR(255) NOT NULL COMMENT '来源 Excel 文件',
  `source_sheet` VARCHAR(128) DEFAULT NULL COMMENT '来源工作表',
  `report_time` DATETIME DEFAULT NULL COMMENT '上报时间',
  `report_time_raw` VARCHAR(128) DEFAULT NULL COMMENT '原始上报时间文本',
  `report_value` DOUBLE DEFAULT NULL COMMENT '上报值（数值化）',
  `report_value_raw` VARCHAR(128) DEFAULT NULL COMMENT '原始上报值文本',
  `monitor_value` DOUBLE DEFAULT NULL COMMENT '监控值（数值化）',
  `monitor_value_raw` VARCHAR(128) DEFAULT NULL COMMENT '原始监控值文本',
  `unit` VARCHAR(64) DEFAULT NULL COMMENT '单位',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_battery_measurement_row_hash` (`row_hash`),
  KEY `idx_battery_measurement_series` (`series_id`),
  KEY `idx_battery_measurement_machine_room_time` (`machine_room_id`, `report_time`),
  KEY `idx_battery_measurement_time` (`report_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='battery 原始测点数据';

CREATE TABLE IF NOT EXISTS `battery_anomaly_result` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `result_dataset` VARCHAR(255) NOT NULL COMMENT '结果数据集标识，如 output_ups_型号1',
  `result_kind` VARCHAR(32) NOT NULL COMMENT '结果类型：single_cell/pack_voltage',
  `record_hash` CHAR(40) NOT NULL COMMENT '结果记录哈希，避免重复导入',
  `raw_dataset` VARCHAR(255) DEFAULT NULL COMMENT '关联原始数据集标识',
  `source_category` VARCHAR(64) DEFAULT NULL COMMENT '来源大类',
  `source_subtype` VARCHAR(128) DEFAULT NULL COMMENT '来源子类',
  `series_id` VARCHAR(512) NOT NULL COMMENT '序列稳定主键',
  `machine_room_id` INT DEFAULT NULL COMMENT '关联 machine_room.id，按机房名称/城市匹配',
  `province` VARCHAR(64) DEFAULT NULL COMMENT '省',
  `city` VARCHAR(64) DEFAULT NULL COMMENT '市',
  `site_name` VARCHAR(255) DEFAULT NULL COMMENT '站点',
  `building_name` VARCHAR(255) DEFAULT NULL COMMENT '楼栋',
  `room_name` VARCHAR(255) NOT NULL COMMENT '机房',
  `device_type` VARCHAR(128) DEFAULT NULL COMMENT '设备类型',
  `device_name` VARCHAR(255) NOT NULL COMMENT '设备',
  `point_type` VARCHAR(128) DEFAULT NULL COMMENT '测点类型',
  `measure_name` VARCHAR(255) NOT NULL COMMENT '监控量',
  `group_name` VARCHAR(128) DEFAULT NULL COMMENT '组别',
  `point_code` VARCHAR(128) DEFAULT NULL COMMENT '测点编码',
  `source_file` VARCHAR(255) DEFAULT NULL COMMENT '来源 Excel 文件',
  `source_sheet` VARCHAR(128) DEFAULT NULL COMMENT '来源工作表',
  `report_time` DATETIME DEFAULT NULL COMMENT '上报时间',
  `report_value` DOUBLE DEFAULT NULL COMMENT '上报值',
  `unit` VARCHAR(64) DEFAULT NULL COMMENT '单位',
  `monitor_value` DOUBLE DEFAULT NULL COMMENT '监控值',
  `n_points` INT DEFAULT NULL COMMENT '用于分析的点数',
  `duration_s` DOUBLE DEFAULT NULL COMMENT '分析窗口时长（秒）',
  `window_found` TINYINT(1) DEFAULT NULL COMMENT '是否成功截取放电窗口',
  `v_min` DOUBLE DEFAULT NULL COMMENT '最小电压',
  `v_max` DOUBLE DEFAULT NULL COMMENT '最大电压',
  `v_range` DOUBLE DEFAULT NULL COMMENT '电压范围',
  `label` INT DEFAULT NULL COMMENT 'DBSCAN 标签',
  `anomaly_original` TINYINT(1) DEFAULT NULL COMMENT '原始异常判定',
  `is_far` TINYINT(1) DEFAULT NULL COMMENT '是否远离簇中心',
  `is_knn_high` TINYINT(1) DEFAULT NULL COMMENT 'KNN 分数是否过高',
  `knn_score` DOUBLE DEFAULT NULL COMMENT 'KNN 离群分数',
  `cluster_dist` DOUBLE DEFAULT NULL COMMENT '簇中心距离',
  `best_shift` INT DEFAULT NULL COMMENT '最佳对齐平移',
  `v_mean` DOUBLE DEFAULT NULL COMMENT '平均电压特征',
  `d2_std` DOUBLE DEFAULT NULL COMMENT '二阶差分标准差特征',
  `zigzag` DOUBLE DEFAULT NULL COMMENT '锯齿特征',
  `shift_abs` DOUBLE DEFAULT NULL COMMENT '平移绝对值特征',
  `dbscan_eps` DOUBLE DEFAULT NULL COMMENT 'DBSCAN eps',
  `dbscan_noise_ratio` DOUBLE DEFAULT NULL COMMENT 'DBSCAN 噪声占比',
  `dbscan_clusters` INT DEFAULT NULL COMMENT 'DBSCAN 聚类数',
  `hard_anomaly` TINYINT(1) DEFAULT NULL COMMENT '硬阈值异常',
  `similarity_group` DOUBLE DEFAULT NULL COMMENT '组内相似度',
  `similarity_keep` TINYINT(1) DEFAULT NULL COMMENT '是否因组内相似而保留',
  `anomaly_flag` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '最终异常标记',
  `source_csv_path` VARCHAR(512) DEFAULT NULL COMMENT '来源 CSV 路径',
  `imported_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '导入时间',
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_battery_anomaly_record_hash` (`record_hash`),
  KEY `idx_battery_anomaly_dataset_kind` (`result_dataset`, `result_kind`),
  KEY `idx_battery_anomaly_series` (`series_id`),
  KEY `idx_battery_anomaly_machine_room` (`machine_room_id`),
  KEY `idx_battery_anomaly_flag` (`anomaly_flag`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='battery 阶段一异常检测结果';

CREATE TABLE IF NOT EXISTS `battery_shape_classification` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `result_dataset` VARCHAR(255) NOT NULL COMMENT '结果数据集标识，如 output_ups_型号1_原始三分类_v2/单体XX电压',
  `shape_source` VARCHAR(32) NOT NULL COMMENT '分类来源：raw_curve/plot_png',
  `record_hash` CHAR(40) NOT NULL COMMENT '结果记录哈希，避免重复导入',
  `raw_dataset` VARCHAR(255) DEFAULT NULL COMMENT '关联原始数据集标识',
  `source_category` VARCHAR(64) DEFAULT NULL COMMENT '来源大类',
  `source_subtype` VARCHAR(128) DEFAULT NULL COMMENT '来源子类',
  `series_id` VARCHAR(512) DEFAULT NULL COMMENT '序列稳定主键',
  `machine_room_id` INT DEFAULT NULL COMMENT '关联 machine_room.id，按机房名称/城市匹配',
  `province` VARCHAR(64) DEFAULT NULL COMMENT '省',
  `city` VARCHAR(64) DEFAULT NULL COMMENT '市',
  `site_name` VARCHAR(255) DEFAULT NULL COMMENT '站点',
  `building_name` VARCHAR(255) DEFAULT NULL COMMENT '楼栋',
  `room_name` VARCHAR(255) DEFAULT NULL COMMENT '机房',
  `device_type` VARCHAR(128) DEFAULT NULL COMMENT '设备类型',
  `device_name` VARCHAR(255) DEFAULT NULL COMMENT '设备',
  `point_type` VARCHAR(128) DEFAULT NULL COMMENT '测点类型',
  `measure_name` VARCHAR(255) DEFAULT NULL COMMENT '监控量',
  `group_name` VARCHAR(128) DEFAULT NULL COMMENT '组别',
  `point_code` VARCHAR(128) DEFAULT NULL COMMENT '测点编码',
  `source_file` VARCHAR(255) DEFAULT NULL COMMENT '来源 Excel 文件',
  `source_sheet` VARCHAR(128) DEFAULT NULL COMMENT '来源工作表',
  `report_time` DATETIME DEFAULT NULL COMMENT '上报时间',
  `report_value` DOUBLE DEFAULT NULL COMMENT '上报值',
  `unit` VARCHAR(64) DEFAULT NULL COMMENT '单位',
  `monitor_value` DOUBLE DEFAULT NULL COMMENT '监控值',
  `n_points` INT DEFAULT NULL COMMENT '用于分类的点数',
  `duration_s` DOUBLE DEFAULT NULL COMMENT '窗口时长（秒）',
  `window_found` TINYINT(1) DEFAULT NULL COMMENT '是否成功截取放电窗口',
  `v_min` DOUBLE DEFAULT NULL COMMENT '最小电压',
  `v_max` DOUBLE DEFAULT NULL COMMENT '最大电压',
  `v_range` DOUBLE DEFAULT NULL COMMENT '电压范围',
  `best_shift` INT DEFAULT NULL COMMENT '最佳对齐平移',
  `valley_x` DOUBLE DEFAULT NULL COMMENT '谷底位置',
  `start_level` DOUBLE DEFAULT NULL COMMENT '起点电平',
  `valley_level` DOUBLE DEFAULT NULL COMMENT '谷底电平',
  `end_level` DOUBLE DEFAULT NULL COMMENT '终点电平',
  `drop_value` DOUBLE DEFAULT NULL COMMENT '下跌幅度',
  `recover_value` DOUBLE DEFAULT NULL COMMENT '回升幅度',
  `recover_ratio` DOUBLE DEFAULT NULL COMMENT '回升比',
  `pre_down_ratio` DOUBLE DEFAULT NULL COMMENT '谷底前下降比例',
  `post_up_ratio` DOUBLE DEFAULT NULL COMMENT '谷底后上升比例',
  `sign_change_ratio` DOUBLE DEFAULT NULL COMMENT '趋势切换比例',
  `dynamic_range` DOUBLE DEFAULT NULL COMMENT '动态范围',
  `end_drop` DOUBLE DEFAULT NULL COMMENT '尾部突降量',
  `shape_class` VARCHAR(64) NOT NULL COMMENT '形状分类编码',
  `shape_class_cn` VARCHAR(64) DEFAULT NULL COMMENT '形状分类中文名',
  `reason` TEXT COMMENT '分类原因',
  `generated_plot` VARCHAR(512) DEFAULT NULL COMMENT '生成的分类图路径',
  `src_path` VARCHAR(512) DEFAULT NULL COMMENT '来源 PNG 路径',
  `copied_path` VARCHAR(512) DEFAULT NULL COMMENT '分类后复制路径',
  `source_csv_path` VARCHAR(512) DEFAULT NULL COMMENT '来源 CSV 路径',
  `imported_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '导入时间',
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_battery_shape_record_hash` (`record_hash`),
  KEY `idx_battery_shape_dataset_source` (`result_dataset`, `shape_source`),
  KEY `idx_battery_shape_series` (`series_id`),
  KEY `idx_battery_shape_machine_room` (`machine_room_id`),
  KEY `idx_battery_shape_class` (`shape_class`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='battery 阶段二形状分类结果';

DROP VIEW IF EXISTS `battery_anomaly_group_summary_v`;
CREATE VIEW `battery_anomaly_group_summary_v` AS
SELECT
  `result_dataset`,
  `result_kind`,
  `source_file`,
  `source_sheet`,
  `room_name`,
  `device_name`,
  COUNT(DISTINCT `series_id`) AS `total_series`,
  SUM(CASE WHEN `anomaly_flag` = 1 THEN 1 ELSE 0 END) AS `anomaly_series`,
  MAX(`knn_score`) AS `max_knn`,
  CASE
    WHEN COUNT(DISTINCT `series_id`) = 0 THEN 0
    ELSE SUM(CASE WHEN `anomaly_flag` = 1 THEN 1 ELSE 0 END) / COUNT(DISTINCT `series_id`)
  END AS `anomaly_ratio`
FROM `battery_anomaly_result`
GROUP BY
  `result_dataset`,
  `result_kind`,
  `source_file`,
  `source_sheet`,
  `room_name`,
  `device_name`;
